version: '3.8'

services:
  db:
    container_name: od_db
    image: mysql:8
    restart: always
    volumes:
      - od-db:/var/lib/mysql
    ports:
      - target: 3306
        published: 3309
    environment:
      MYSQL_DATABASE: oddiiydb
      MYSQL_USER: gumbum
      MYSQL_PASSWORD: gumpass
      MYSQL_ROOT_PASSWORD: oddiiyroot
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - od-app

  app:
    container_name: od_app
    user: 1000:1000
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www/${PROJECT_NAME}
      - ${PROJECT_PATH}/storage:/var/www/${PROJECT_NAME}/storage
    expose:
      - "9000"

    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - od-app

  nginx:
    container_name: od_nginx
    image: nginx:latest
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ${PROJECT_PATH}:/var/www/${PROJECT_NAME}
      - ${PROJECT_PATH}/storage:/var/www/${PROJECT_NAME}/storage
      - ${PROJECT_PATH}/docker/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_healthy
    networks:
      - od-app

volumes:
  od-db:

networks:
  od-app:
    driver: bridge
