services:
  nginx:
    container_name: od_nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 8000
        protocol: tcp
    volumes:
      - ${PROJECT_PATH}:/var/www/${PROJECT_NAME}
      - ${PROJECT_PATH}/storage:/var/www/${PROJECT_NAME}/storage
      - ${PROJECT_PATH}/docker/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - od-app
      - od-net

  app:
    container_name: od_app
    user: 1000:1000
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www/${PROJECT_NAME}
      - ${PROJECT_PATH}/storage:/var/www/${PROJECT_NAME}/storage
    depends_on:
      - db
    networks:
      - od-app
      - od-net

  db:
    container_name: od_db
    image: mysql:8
    restart: always
    volumes:
      - od-db:/var/lib/mysql
    ports:
      - target: 3306
        published: 3309
    environment:
      MYSQL_DATABASE: oddiiydb
      MYSQL_USER: gumbum
      MYSQL_PASSWORD: gumpass
      MYSQL_ROOT_PASSWORD: oddiiyroot
    networks:
      - od-app

volumes:
  od-db:

networks:
  od-app:
    driver: bridge
  od-net:
    name: "od-net"
    external: true
